server:
  port: 8080
spring:
  application:
    name: user_new
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=GMT%2b8
    username: root
    password: seckill
#  mvc:
#    pathmatch:
#      #matching-strategy: ant_path_matcher
  redis:
    host: 127.0.0.1
    port: 6379
    password: seckill
    timeout: 30000
    jedis:
      pool:
        max-active: 500
        max-idle: 10
        min-idle: 0
        max-wait: -1
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: localhost:9100
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
